### ISSUE TITLE
Practica Contrato

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-team-remi#1]
[Reporte de Práctica 10.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-team-remi/files/10189240/Reporte.de.Practica.10.pdf)

**Comment by Band-hi** [comment]
@Yabin-2021
@Brisa-4
@JazminloRI
Adjunto reporte de practica correspondiente a la practica 10

**Comment by Yabin-2021** [comment]
Enterado, ya lo reviso!!

**Comment by Yabin-2021** [comment]
Buen trabajo y revisado!
50%

**Comment by Band-hi** [comment]
@josealfredo79 de igual forma ya está calificada nuestra práctica

**Comment by josealfredo79** [comment]
Bien hecho y revisado
